language: dart
dart:
- stable

sudo: required
addons:
  chrome: stable

jobs:
  include:
    - stage: analyze
      script:
        - cd webapp
        - datanalyzer --fatal-warnings .

  - stage: test
      script:
        - test: --platform chrome

stages:
  - analyze
  - test
  
cache:
  directories:
    - $HOME/.pub-cache
