name: CodaV2
version: 2.0.0
description: Coda V2

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  firebase: ^5.0.0
  http: ^0.11.3

dev_dependencies:
  build_runner: any
  build_web_compilers: any
  test: ^1.0.0
