name: CodaV2
version: 2.0.0
description: Coda V2

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  firebase: ^5.0.0
  http: ^0.11.3
  gcloud: ^0.6.0

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
  test: ^1.0.0
